language: generic 
sudo: required

services:
  - docker
   
before_install:
  - docker build -t hanabadr/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true hanabadr/react-test npm test
  
after_success:
  - docker build -t hanabadr/multi-client ./client
  - docker build -t hanabadr/multi-nginx ./nginx
  - docker build -t hanabadr/multi-server ./server
  - docker build -t hanabadr/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push multi-client 
  - docker push multi-nginx 
  - docker push multi-server 
  - docker push multi-worker